//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogVacay_Anubis_1509.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        public Dog()
        {
            this.Stays1 = new HashSet<Stay>();
        }
    
        public int DogId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public string Breed { get; set; }
        public Nullable<float> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> HumanId1 { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual ICollection<Stay> Stays1 { get; set; }
    }
}
