//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogVacay_Anubis_1509.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DogVacayDataEntities : DbContext
    {
        public DogVacayDataEntities()
            : base("name=DogVacayDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<Human> Humans { get; set; }
        public virtual DbSet<Stay> Stays { get; set; }
    }
}
