//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogVacay_Anubis_1509.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Human
    {
        public Human()
        {
            this.Dogs = new HashSet<Dog>();
        }
    
        public int HumanId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Dog> Dogs { get; set; }
    }
}
